### ISSUE TITLE
[!] No podspec found for `file_previewer` in `.symlinks/plugins/file_previewer/ios`

### ISSUE THREAD

**Issue by TheGadri** [DutchCodingCompany/file_preview#3] opened 2022-05-09 13:51 UTC
I added the plugin and hit run which resulted in this.

[!] No podspec found for `file_previewer` in `.symlinks/plugins/file_previewer/ios`

It only works when you add the plugin while the app is already running but not on building the app.

**Comment by stijnie2210** [comment] 2022-05-16 11:20
Hi @TheGadri ,

Thanks for addressing this issue, this has been fixed in version 0.0.5 on pub.dev and was caused by a plugin name mismatch.

https://pub.dev/packages/file_previewer/versions/0.0.5

**Closed as completed by stijnie2210** 2022-05-16 11:20 UTC
